name: Review Comment
description: Technical review comments on UBT alpha baseline derivation
title: "[Review] "
labels: ["review", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reviewing the UBT alpha baseline derivation! Please provide detailed technical feedback to help improve the rigor and clarity of the work.
        
  - type: input
    id: section
    attributes:
      label: Section/Appendix
      description: Which section or appendix does this comment apply to?
      placeholder: e.g., Appendix CT Section 3.2, Appendix Î± equation 51
    validations:
      required: true
      
  - type: input
    id: equation
    attributes:
      label: Equation Label (if applicable)
      description: Specific equation reference
      placeholder: e.g., eq:B-with-RUBT, thm:RUBT-equals-one
    validations:
      required: false
      
  - type: dropdown
    id: claim-type
    attributes:
      label: Type of Claim
      description: What type of statement is being questioned?
      options:
        - Mathematical derivation
        - Physical interpretation
        - Assumption/axiom
        - Numerical result
        - Experimental prediction
        - Other
    validations:
      required: true
      
  - type: textarea
    id: issue-description
    attributes:
      label: Description of Issue
      description: Clearly describe the technical issue, error, or question
      placeholder: Explain what you believe is incorrect, unclear, or questionable
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: How can this issue be verified or reproduced?
      placeholder: |
        1. Open file X
        2. Look at equation Y
        3. Apply definition from Z
        4. Observe inconsistency/error
    validations:
      required: true
      
  - type: textarea
    id: expected-actual
    attributes:
      label: Expected vs. Actual
      description: What do you expect vs. what the document states?
      placeholder: |
        Expected: [what the correct result should be]
        Actual: [what the document currently states]
    validations:
      required: true
      
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix (optional)
      description: If you have a suggested correction, provide it here
      placeholder: Mathematical expression, reworded statement, or clarification
    validations:
      required: false
      
  - type: textarea
    id: references
    attributes:
      label: References
      description: Cite any relevant papers, textbooks, or other sources supporting your comment
      placeholder: |
        - Peskin & Schroeder, Introduction to QFT, Chapter X
        - arXiv:XXXX.XXXXX
    validations:
      required: false
      
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Add any supporting calculations, diagrams, or screenshots
      placeholder: Drag and drop files here
    validations:
      required: false
      
  - type: checkboxes
    id: review-checklist
    attributes:
      label: Reviewer Checklist
      description: Please confirm you have:
      options:
        - label: Read the relevant section(s) in detail
          required: true
        - label: Checked related appendices and definitions
          required: true
        - label: Provided specific references (equations, page numbers, etc.)
          required: true
        - label: Suggested a constructive path forward (if applicable)
          required: false
