#!/usr/bin/env python3
"""
Generate LaTeX constants file from external reference sources.
This file creates tex/reference_constants.tex with macros for external reference values.

These are REFERENCE values (e.g., from CODATA), not computed UBT values.
Use this for comparison purposes only in canonical documents.
For computed values, use data/*.csv files.

Usage:
    python tools/generate_reference_constants.py
"""
from pathlib import Path

# External reference values (CODATA 2018)
# These are NOT computed from UBT - they are experimental reference values
REFERENCE_CONSTANTS = {
    "AlphaInvCODATA": ("137.035999084", "Fine structure constant inverse (CODATA 2018)"),
    "ElectronMassMeVCODATA": ("0.5109989461", "Electron mass in MeV (CODATA 2018)"),
    "MuonMassMeVCODATA": ("105.6583745", "Muon mass in MeV (CODATA 2018)"),
    "TauMassMeVCODATA": ("1776.86", "Tau mass in MeV (PDG 2020)"),
}

def generate_latex_constants():
    """Generate LaTeX file with reference constants."""
    output_dir = Path("tex")
    output_dir.mkdir(exist_ok=True, parents=True)
    
    output_file = output_dir / "reference_constants.tex"
    
    with output_file.open("w", encoding="utf-8") as f:
        f.write("% AUTO-GENERATED - DO NOT EDIT BY HAND\n")
        f.write("% Generated by tools/generate_reference_constants.py\n")
        f.write("%\n")
        f.write("% IMPORTANT: These are EXTERNAL REFERENCE values (CODATA, PDG)\n")
        f.write("% NOT computed from UBT. Use for comparison only.\n")
        f.write("% For UBT-computed values, use data/*.csv files.\n")
        f.write("%\n\n")
        
        for macro_name, (value, description) in REFERENCE_CONSTANTS.items():
            f.write(f"% {description}\n")
            f.write(f"\\newcommand{{\\{macro_name}}}{{{value}}}\n\n")
    
    print(f"Generated {output_file} with {len(REFERENCE_CONSTANTS)} reference constants")
    print("Include in LaTeX with: \\input{tex/reference_constants}")
    print("\nWARNING: These are external reference values, not UBT computations")

if __name__ == "__main__":
    generate_latex_constants()
