#!/usr/bin/env python3
"""Exact checks for the post-v10.2 GR subclosures.

Verifies:
1. The Cartan torsion map T^a -> epsilon_abcd T^a wedge e^b has rank 24
   at an orthonormal tetrad, hence is pointwise injective for nondegenerate e.
2. J(X) = -conj(X^sharp) is an anti-linear involution whose fixed set is the
   Lorentz slice (pure-imaginary scalar, real vector coefficients).
3. A psi-flow generated by an eta-antisymmetric Lorentz matrix leaves
   g = e eta e^T invariant.
4. The augmented-connection curvature identity for
   D_mu Theta = partial_mu Theta + A_mu Theta - Theta B_mu = s E_mu.

This does NOT derive the Palatini action, prove PDE well-posedness, prove
Lovelock's theorem, or solve the self-consistent curved UBT equations.
"""
from __future__ import annotations

from itertools import combinations

import sympy as sp


def permutation_sign(seq: tuple[int, ...]) -> int:
    if len(set(seq)) != len(seq):
        return 0
    inv = sum(1 for i in range(len(seq)) for j in range(i + 1, len(seq)) if seq[i] > seq[j])
    return -1 if inv % 2 else 1


def epsilon4(a: int, b: int, c: int, d: int) -> int:
    return permutation_sign((a, b, c, d))


def wedge_sign(indices: tuple[int, ...]) -> tuple[int, tuple[int, ...]]:
    if len(set(indices)) != len(indices):
        return 0, tuple(sorted(indices))
    return permutation_sign(indices), tuple(sorted(indices))


def cartan_torsion_rank_check() -> None:
    # T^a = 1/2 T^a_{mn} dx^m wedge dx^n; use m<n as 24 variables.
    tvars: list[sp.Symbol] = []
    tidx: dict[tuple[int, int, int], int] = {}
    for a in range(4):
        for m, n in combinations(range(4), 2):
            tidx[(a, m, n)] = len(tvars)
            tvars.append(sp.Symbol(f"T{a}{m}{n}"))

    # Equations Q_cd = epsilon_abcd T^a wedge dx^b, expanded in 3-form basis.
    triples = list(combinations(range(4), 3))
    equations: list[sp.Expr] = []
    for c, d in combinations(range(4), 2):
        coeffs = {triple: sp.S.Zero for triple in triples}
        for a in range(4):
            for b in range(4):
                eps = epsilon4(a, b, c, d)
                if eps == 0:
                    continue
                for m, n in combinations(range(4), 2):
                    sign, triple = wedge_sign((m, n, b))
                    if sign:
                        coeffs[triple] += eps * sign * tvars[tidx[(a, m, n)]]
        equations.extend(sp.expand(coeffs[t]) for t in triples)

    matrix, _ = sp.linear_eq_to_matrix(equations, tvars)
    assert matrix.shape == (24, 24), matrix.shape
    assert matrix.rank() == 24


def lorentz_slice_involution_check() -> None:
    r = sp.symbols("r0:4", real=True)
    im = sp.symbols("i0:4", real=True)
    coeffs = [r[k] + sp.I * im[k] for k in range(4)]

    # J(a0,a1,a2,a3) = (-conj(a0), conj(a1), conj(a2), conj(a3)).
    j = [-sp.conjugate(coeffs[0])] + [sp.conjugate(c) for c in coeffs[1:]]
    jj = [-sp.conjugate(j[0])] + [sp.conjugate(c) for c in j[1:]]
    assert all(sp.simplify(jj[k] - coeffs[k]) == 0 for k in range(4))

    # X=JX iff Re(a0)=0 and Im(ak)=0 for k=1,2,3.
    fixed_differences = [sp.expand(coeffs[k] - j[k]) for k in range(4)]
    assert sp.simplify(fixed_differences[0] - 2 * r[0]) == 0
    for k in range(1, 4):
        assert sp.simplify(fixed_differences[k] - 2 * sp.I * im[k]) == 0


def psi_lorentz_flow_check() -> None:
    eta = sp.diag(-1, 1, 1, 1)
    # Build Lambda = eta^{-1} omega with omega_ab antisymmetric, so
    # Lambda^T eta + eta Lambda = 0.
    params = sp.symbols("w0:6", real=True)
    omega = sp.zeros(4)
    p = 0
    for a, b in combinations(range(4), 2):
        omega[a, b] = params[p]
        omega[b, a] = -params[p]
        p += 1
    Lambda = eta.inv() * omega
    assert sp.simplify(Lambda.T * eta + eta * Lambda) == sp.zeros(4)

    e = sp.Matrix(4, 4, sp.symbols("e0:16"))
    dg = sp.simplify((e * Lambda.T) * eta * e.T + e * eta * (e * Lambda.T).T)
    # If rows e_mu transform as de_mu^a = Lambda^a_b e_mu^b,
    # in matrix row convention de = e Lambda^T.
    assert dg == sp.zeros(4)


def msimplify(m: sp.Matrix) -> sp.Matrix:
    return m.applyfunc(sp.simplify)


def augmented_curvature_check() -> None:
    x, y = sp.symbols("x y", real=True)
    s = sp.Symbol("s", nonzero=True)
    theta = sp.Matrix([[1 + x, y], [x * y, 2 + x - y]])
    A0 = sp.Matrix([[x, 1], [y, -x]])
    A1 = sp.Matrix([[y, x], [1 + y, -y]])
    B0 = sp.Matrix([[0, x], [y, 1]])
    B1 = sp.Matrix([[x * y, 1], [x, -x * y]])
    coords = [x, y]
    As = [A0, A1]
    Bs = [B0, B1]

    def D(mu: int, z: sp.Matrix) -> sp.Matrix:
        return msimplify(z.diff(coords[mu]) + As[mu] * z - z * Bs[mu])

    E = [msimplify(D(mu, theta) / s) for mu in range(2)]
    FA = msimplify(A1.diff(x) - A0.diff(y) + A0 * A1 - A1 * A0)
    FB = msimplify(B1.diff(x) - B0.diff(y) + B0 * B1 - B1 * B0)
    left = msimplify(FA * theta - theta * FB)
    right = msimplify(s * (D(0, E[1]) - D(1, E[0])))
    assert msimplify(left - right) == sp.zeros(2)

    # Vectorized augmented block identity.
    # vec(A X - X B) = (I kron A - B^T kron I) vec(X), column-major.
    I2 = sp.eye(2)
    C0 = sp.kronecker_product(I2, A0) - sp.kronecker_product(B0.T, I2)
    C1 = sp.kronecker_product(I2, A1) - sp.kronecker_product(B1.T, I2)

    def vec_col(m: sp.Matrix) -> sp.Matrix:
        return sp.Matrix([m[0, 0], m[1, 0], m[0, 1], m[1, 1]])

    E0v, E1v = vec_col(E[0]), vec_col(E[1])
    Z14 = sp.zeros(1, 4)
    Chat0 = C0.row_join(-s * E0v).col_join(Z14.row_join(sp.zeros(1, 1)))
    Chat1 = C1.row_join(-s * E1v).col_join(Z14.row_join(sp.zeros(1, 1)))
    Fhat = msimplify(Chat1.diff(x) - Chat0.diff(y) + Chat0 * Chat1 - Chat1 * Chat0)
    Y = vec_col(theta).col_join(sp.ones(1, 1))
    assert msimplify(Fhat * Y) == sp.zeros(5, 1)


def main() -> None:
    cartan_torsion_rank_check()
    lorentz_slice_involution_check()
    psi_lorentz_flow_check()
    augmented_curvature_check()
    print("REMAINING GR SUBCLOSURES CHECK: ALL CHECKS PASSED")
    print("  Cartan torsion map: rank 24/24")
    print("  Lorentz slice: fixed set of J(X)=-conj(X^sharp)")
    print("  psi Lorentz-gauge flow: partial_psi g = 0")
    print("  augmented connection: exact curvature/compatibility identity")
    print("  NOT TESTED: action origin, PDE well-posedness, Lovelock theorem, self-consistent curved solution")


if __name__ == "__main__":
    main()
