#!/usr/bin/env python3
"""Exact Clifford and Lorentz-bivector certificates for the Palatini selector.

Checks the canonical UBT 4x4 block lift on the Lorentz basis, the grading trace
identity producing epsilon_abcd, uniqueness (up to scale) of the grading among
matrices anticommuting with all four Clifford generators, and the two-dimensional
space of symmetric Lorentz-invariant bilinear forms on bivectors.
"""

from __future__ import annotations

import sympy as sp

I = sp.I
ETA = sp.diag(-1, 1, 1, 1)
PAIRS = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]


def sharp2(x: sp.Matrix) -> sp.Matrix:
    return sp.Matrix([[x[1, 1], -x[0, 1]], [-x[1, 0], x[0, 0]]])


def block_lift(x: sp.Matrix) -> sp.Matrix:
    zero = sp.zeros(2)
    return zero.row_join(x).col_join(sharp2(x).row_join(zero))


def canonical_gammas() -> tuple[list[sp.Matrix], sp.Matrix]:
    sigma1 = sp.Matrix([[0, 1], [1, 0]])
    sigma2 = sp.Matrix([[0, -I], [I, 0]])
    sigma3 = sp.Matrix([[1, 0], [0, -1]])
    identity = sp.eye(2)
    e = [I * identity, -I * sigma1, -I * sigma2, -I * sigma3]
    gammas = [block_lift(x) for x in e]
    grading = sp.diag(1, 1, -1, -1)
    return gammas, grading


def epsilon4(a: int, b: int, c: int, d: int) -> int:
    if len({a, b, c, d}) < 4:
        return 0
    p = [a, b, c, d]
    inversions = sum(p[i] > p[j] for i in range(4) for j in range(i + 1, 4))
    return -1 if inversions % 2 else 1


def lorentz_generators_vector() -> list[sp.Matrix]:
    generators = []
    for a, b in PAIRS:
        m = sp.zeros(4)
        m[a, b] = ETA[a, a]
        m[b, a] = -ETA[b, b]
        assert m.T * ETA + ETA * m == sp.zeros(4)
        generators.append(m)
    return generators


def wedge2_generator(m: sp.Matrix) -> sp.Matrix:
    index = {pair: i for i, pair in enumerate(PAIRS)}
    out = sp.zeros(6)
    for column, (a, b) in enumerate(PAIRS):
        for c in range(4):
            coefficient = m[c, a]
            if coefficient and c != b:
                pair = tuple(sorted((c, b)))
                sign = 1 if c < b else -1
                out[index[pair], column] += sign * coefficient
        for c in range(4):
            coefficient = m[c, b]
            if coefficient and a != c:
                pair = tuple(sorted((a, c)))
                sign = 1 if a < c else -1
                out[index[pair], column] += sign * coefficient
    return out


def invariant_bivector_forms_dimension() -> tuple[int, list[sp.Matrix]]:
    variables = []
    b = sp.zeros(6)
    for row in range(6):
        for column in range(row, 6):
            symbol = sp.symbols(f"b{row}{column}")
            variables.append(symbol)
            b[row, column] = symbol
            b[column, row] = symbol

    equations = []
    for generator in map(wedge2_generator, lorentz_generators_vector()):
        equations.extend(list(generator.T * b + b * generator))
    matrix, _ = sp.linear_eq_to_matrix(equations, variables)
    nullspace = matrix.nullspace()
    forms = [sp.simplify(b.subs(dict(zip(variables, vector)))) for vector in nullspace]
    return len(nullspace), forms


def verify() -> None:
    gammas, grading = canonical_gammas()

    # Canonical Clifford relation.
    for a in range(4):
        for b in range(4):
            anticommutator = sp.simplify((gammas[a] * gammas[b] + gammas[b] * gammas[a]) / 2)
            assert anticommutator == ETA[a, b] * sp.eye(4)

    assert grading**2 == sp.eye(4)
    for gamma in gammas:
        assert grading * gamma + gamma * grading == sp.zeros(4)

    # Graded trace is exactly the oriented epsilon tensor.
    for a in range(4):
        for b in range(4):
            for c in range(4):
                for d in range(4):
                    graded = sp.trace(grading * gammas[a] * gammas[b] * gammas[c] * gammas[d])
                    assert sp.simplify(graded + 4 * I * epsilon4(a, b, c, d)) == 0

                    ungraded = sp.trace(gammas[a] * gammas[b] * gammas[c] * gammas[d])
                    expected = 4 * (
                        ETA[a, b] * ETA[c, d]
                        - ETA[a, c] * ETA[b, d]
                        + ETA[a, d] * ETA[b, c]
                    )
                    assert sp.simplify(ungraded - expected) == 0

    # A general complex 4x4 matrix that anticommutes with every gamma is a
    # one-complex-dimensional space, generated by Gamma_*.
    symbols = sp.symbols("z0:16")
    z = sp.Matrix(4, 4, symbols)
    equations = []
    for gamma in gammas:
        equations.extend(list(z * gamma + gamma * z))
    matrix, _ = sp.linear_eq_to_matrix(equations, symbols)
    assert len(matrix.nullspace()) == 1
    representative = sp.Matrix(4, 4, matrix.nullspace()[0])
    # Normalize by the (0,0) entry and compare with the canonical grading.
    assert representative[0, 0] != 0
    representative = sp.simplify(representative / representative[0, 0])
    assert representative == grading

    # Lorentz-invariant symmetric bilinear forms on bivectors form exactly a
    # two-dimensional space: metric/Holst and epsilon/Palatini channels.
    dimension, forms = invariant_bivector_forms_dimension()
    assert dimension == 2

    metric_form = sp.diag(-1, -1, -1, 1, 1, 1)
    epsilon_form = sp.Matrix(
        [
            [0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, -1, 0],
            [0, 0, 0, 1, 0, 0],
            [0, 0, 1, 0, 0, 0],
            [0, -1, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0],
        ]
    )
    invariant_span = sp.Matrix.hstack(*(form.reshape(36, 1) for form in forms))
    assert invariant_span.rank() == 2
    assert sp.Matrix.hstack(invariant_span, metric_form.reshape(36, 1)).rank() == 2
    assert sp.Matrix.hstack(invariant_span, epsilon_form.reshape(36, 1)).rank() == 2
    assert sp.Matrix.hstack(metric_form.reshape(36, 1), epsilon_form.reshape(36, 1)).rank() == 2

    print("PASS: canonical block lift satisfies Cl(1,3) with signature (-,+,+,+)")
    print("PASS: Tr(Gamma_* Gamma_a Gamma_b Gamma_c Gamma_d) = -4 i epsilon_abcd")
    print("PASS: normalized grading anticommutant is unique up to sign/scale")
    print("PASS: Lorentz-invariant symmetric bivector pairings have dimension 2")


if __name__ == "__main__":
    verify()
